[tool.poetry]
name = "koila"
version = "0.2.0"
description = "Prevent PyTorch's `CUDA error out of memory` in a few lines of code."
authors = ["rentruewang <patrick1031wang@gmail.com>"]
license = "MIT"
repository = "https://github.com/rentruewang/koila"

[tool.poetry.dependencies]
numpy = "^1.22.0"
python = "^3.10"
pynvml = "^11.4.1"
rich = "^10.16.1"
torch = "^1.10.1"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.0.0"
black = "^22.12.0"
coverage = "^7.0.5"
isort = "^5.11.4"
mkdocs = "^1.4.2"
mkdocs-git-revision-date-plugin = "^0.3.1"
mkdocs-git-revision-date-localized-plugin = "^0.11.1"
mkdocs-material = "^8.1.3"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["koila"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs",
]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.10"
pythonPlatform = "Linux"
