name: Formatting
on: [push]
jobs:
  format-all:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: ⬇️ Python Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.5.1"

      - name: ⬇️ Python Dependencies
        run: poetry install

      - name: 🏃 autoflake, isort, black
        run: |
          poetry shell
          autoflake -ir $(find -iname "*.py" ! -path '*/.venv/*' ! -name __init__.py) --remove-all-unused-imports
          isort --profile black .
          black .

      - name: ⬆️ Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "🤖 RenTrueWang thinks you forgot to format your code!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
