name: Formatting
on: [push]
jobs:
  format-all:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: ⬇️ Python Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.5.1"

      - name: ⬇️ Python Dependencies
        run: poetry install

      - name: 🏃 autoflake
        run: |
          poetry run autoflake -cr $(find -iname "*.py" ! -path '*/.venv/*' ! -name __init__.py) --remove-all-unused-imports
      
      - name: 🏃 isort
          poetry run isort --check .
        
      - name: 🏃 black
          poetry run black --check .
